import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from supernova_core.i18n import Messages
from supernova_core.models.config import ReportConfig
from supernova_core.models.queue_schemas import (
    AuthVulnerability,
    AuthzVulnerability,
    InjectionVulnerability,
    SsrfVulnerability,
    Vulnerability,
    VulnerabilityQueue,
    XssVulnerability,
)
from supernova_core.utils.file_io import async_path_exists, async_read_file, async_write_file
from supernova_core.utils.paths import resolve_intermediate, resolve_track_deliverable

logger = logging.getLogger(__name__)

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}
CONFIDENCE_ORDER = {"low": 0, "medium": 1, "high": 2}

# 漏洞卡 / 报告文案双语（zh/en 可配，跟随 SUPERNOVA_AGENT_NARRATION_LANG）。
_M = Messages({
    # 通用 entry 标签
    "summary": {"zh": "**摘要:**", "en": "**Summary:**"},
    "notes": {"zh": "**备注:**", "en": "**Notes:**"},
    "vulnerable_location": {"zh": "脆弱位置", "en": "Vulnerable Location"},
    "source_detail": {"zh": "来源详情", "en": "Source Detail"},
    "verdict": {"zh": "判定", "en": "Verdict"},
    "witness_payload": {"zh": "见证载荷", "en": "Witness Payload"},
    "sink_call": {"zh": "Sink 调用", "en": "Sink Call"},
    "concat_occurrences": {"zh": "拼接出现", "en": "Concat Occurrences"},
    "sanitization_observed": {"zh": "净化情况", "en": "Sanitization Observed"},
    "sink_function": {"zh": "Sink 函数", "en": "Sink Function"},
    "render_context": {"zh": "渲染上下文", "en": "Render Context"},
    "encoding_observed": {"zh": "编码情况", "en": "Encoding Observed"},
    "source_endpoint": {"zh": "来源端点", "en": "Source Endpoint"},
    "vulnerable_code_location": {"zh": "脆弱代码位置", "en": "Vulnerable Code Location"},
    "missing_defense": {"zh": "缺失防护", "en": "Missing Defense"},
    "exploitation_hypothesis": {"zh": "利用假设", "en": "Exploitation Hypothesis"},
    "suggested_exploit_technique": {"zh": "建议利用技术", "en": "Suggested Exploit Technique"},
    "endpoint": {"zh": "端点", "en": "Endpoint"},
    "role_context": {"zh": "角色上下文", "en": "Role Context"},
    "guard_evidence": {"zh": "防护证据", "en": "Guard Evidence"},
    "side_effect": {"zh": "副作用", "en": "Side Effect"},
    "reason": {"zh": "原因", "en": "Reason"},
    "minimal_witness": {"zh": "最小见证", "en": "Minimal Witness"},
    "vulnerable_parameter": {"zh": "脆弱参数", "en": "Vulnerable Parameter"},
    # CLASS_CONFIG heading（value = message key）
    "heading_injection": {"zh": "注入漏洞", "en": "Injection Vulnerabilities"},
    "heading_xss": {"zh": "跨站脚本 (XSS)", "en": "Cross-Site Scripting (XSS)"},
    "heading_auth": {"zh": "认证漏洞", "en": "Authentication Vulnerabilities"},
    "heading_authz": {"zh": "授权漏洞", "en": "Authorization Vulnerabilities"},
    "heading_ssrf": {"zh": "服务端请求伪造 (SSRF)", "en": "Server-Side Request Forgery (SSRF)"},
    # none_found_label（value = message key）
    "none_injection": {"zh": "未发现注入漏洞。", "en": "No injection vulnerabilities found."},
    "none_xss": {"zh": "未发现 XSS 漏洞。", "en": "No XSS vulnerabilities found."},
    "none_auth": {"zh": "未发现认证漏洞。", "en": "No authentication vulnerabilities found."},
    "none_authz": {"zh": "未发现授权漏洞。", "en": "No authorization vulnerabilities found."},
    "none_ssrf": {"zh": "未发现 SSRF 漏洞。", "en": "No SSRF vulnerabilities found."},
    # disclaimer + 降级文案
    "disclaimer": {
        "zh": "> **免责声明：** 本报告由自动化安全评估工具生成。所有发现须经合格安全专业人员核实后再采取行动。",
        "en": "> **Disclaimer:** This report was generated by an automated security assessment tool. All findings should be verified by a qualified security professional before taking action.",
    },
    "queue_unreadable": {
        "zh": "> ⚠️ {heading} 队列不可读；该类发现不可用。见日志。",
        "en": "> ⚠️ {heading} queue unreadable; findings unavailable for this class. See logs.",
    },
    "queue_auto_recovered": {
        "zh": "> ⚠️ 队列已自动恢复（{warnings}）。原始队列保留在 `{queue_file}`；请核实数据完整性。",
        "en": "> ⚠️ Queue auto-recovered ({warnings}). Raw queue preserved at `{queue_file}`; verify data integrity.",
    },
    "no_renderable_entries": {
        "zh": "> ⚠️ `{queue_file}` 无可渲染条目（{reason}）。",
        "en": "> ⚠️ No renderable entries in `{queue_file}` ({reason}).",
    },
    "no_parseable_entries": {"zh": "无可解析条目", "en": "no parseable entries"},
    "render_error": {"zh": "### {id} — 渲染错误\n", "en": "### {id} — render error\n"},
})


def _label(key: str) -> str:
    """渲染 `- **<label>:**` 前缀。"""
    return f"- **{_M.get(key)}:**"


@dataclass
class VulnClassConfig:
    heading: str        # message key（运行时 _M.get 解析）
    none_found_label: str  # message key
    queue_file: str
    findings_file: str
    render_entry: Callable


def render_injection_entry(vuln: InjectionVulnerability) -> str:
    # title（spec 2026-08-06）：有 title 拼 ### ID: title；无 title 裸 ### ID（留给 report-executive 第二道补）。
    heading = f"### {vuln.ID}: {vuln.title}" if vuln.title else f"### {vuln.ID}"
    lines = [heading, "", _M.get("summary")]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"{_label('vulnerable_location')} {location}")
    if vuln.source_detail:
        lines.append(f"{_label('source_detail')} {vuln.source_detail}")
    # sink:优先 LLM 实际输出的 sink_function,回退旧 sink_call(语义相同)
    if vuln.sink_function:
        lines.append(f"{_label('sink_function')} {vuln.sink_function}")
    elif vuln.sink_call:
        lines.append(f"{_label('sink_call')} {vuln.sink_call}")
    if vuln.render_context:
        lines.append(f"{_label('render_context')} {vuln.render_context}")
    if vuln.concat_occurrences:
        lines.append(f"{_label('concat_occurrences')} {vuln.concat_occurrences}")
    # 编码/sanitizer:优先 LLM 输出的 encoding_observed,回退旧 sanitization_observed
    if vuln.encoding_observed:
        lines.append(f"{_label('encoding_observed')} {vuln.encoding_observed}")
    elif vuln.sanitization_observed:
        lines.append(f"{_label('sanitization_observed')} {vuln.sanitization_observed}")
    if vuln.verdict:
        lines.append(f"{_label('verdict')} {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"{_label('witness_payload')} {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n{_M.get('notes')} {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_xss_entry(vuln: XssVulnerability) -> str:
    # title（spec 2026-08-06）：有 title 拼 ### ID: title；无 title 裸 ### ID（留给 report-executive 第二道补）。
    heading = f"### {vuln.ID}: {vuln.title}" if vuln.title else f"### {vuln.ID}"
    lines = [heading, "", _M.get("summary")]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"{_label('vulnerable_location')} {location}")
    if vuln.sink_function:
        lines.append(f"{_label('sink_function')} {vuln.sink_function}")
    if vuln.render_context:
        lines.append(f"{_label('render_context')} {vuln.render_context}")
    if vuln.encoding_observed:
        lines.append(f"{_label('encoding_observed')} {vuln.encoding_observed}")
    if vuln.verdict:
        lines.append(f"{_label('verdict')} {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"{_label('witness_payload')} {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n{_M.get('notes')} {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_auth_entry(vuln: AuthVulnerability) -> str:
    # title（spec 2026-08-06）：有 title 拼 ### ID: title；无 title 裸 ### ID（留给 report-executive 第二道补）。
    heading = f"### {vuln.ID}: {vuln.title}" if vuln.title else f"### {vuln.ID}"
    lines = [heading, "", _M.get("summary")]
    if vuln.source_endpoint:
        lines.append(f"{_label('source_endpoint')} {vuln.source_endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"{_label('vulnerable_code_location')} {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"{_label('missing_defense')} {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"{_label('exploitation_hypothesis')} {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"{_label('suggested_exploit_technique')} {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n{_M.get('notes')} {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_authz_entry(vuln: AuthzVulnerability) -> str:
    # title（spec 2026-08-06）：有 title 拼 ### ID: title；无 title 裸 ### ID（留给 report-executive 第二道补）。
    heading = f"### {vuln.ID}: {vuln.title}" if vuln.title else f"### {vuln.ID}"
    lines = [heading, "", _M.get("summary")]
    if vuln.endpoint:
        lines.append(f"{_label('endpoint')} {vuln.endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"{_label('vulnerable_code_location')} {vuln.vulnerable_code_location}")
    if vuln.role_context:
        lines.append(f"{_label('role_context')} {vuln.role_context}")
    if vuln.guard_evidence:
        lines.append(f"{_label('guard_evidence')} {vuln.guard_evidence}")
    if vuln.side_effect:
        lines.append(f"{_label('side_effect')} {vuln.side_effect}")
    if vuln.reason:
        lines.append(f"{_label('reason')} {vuln.reason}")
    if vuln.minimal_witness:
        lines.append(f"{_label('minimal_witness')} {vuln.minimal_witness}")
    if vuln.notes:
        lines.append(f"\n{_M.get('notes')} {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_ssrf_entry(vuln: SsrfVulnerability) -> str:
    # title（spec 2026-08-06）：有 title 拼 ### ID: title；无 title 裸 ### ID（留给 report-executive 第二道补）。
    heading = f"### {vuln.ID}: {vuln.title}" if vuln.title else f"### {vuln.ID}"
    lines = [heading, "", _M.get("summary")]
    if vuln.source_endpoint:
        lines.append(f"{_label('source_endpoint')} {vuln.source_endpoint}")
    if vuln.vulnerable_parameter:
        lines.append(f"{_label('vulnerable_parameter')} {vuln.vulnerable_parameter}")
    if vuln.vulnerable_code_location:
        lines.append(f"{_label('vulnerable_code_location')} {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"{_label('missing_defense')} {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"{_label('exploitation_hypothesis')} {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"{_label('suggested_exploit_technique')} {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n{_M.get('notes')} {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


CLASS_CONFIG: dict[str, VulnClassConfig] = {
    "injection": VulnClassConfig(
        heading="heading_injection",
        none_found_label="none_injection",
        queue_file="injection_exploitation_queue.json",
        findings_file="injection_findings.md",
        render_entry=render_injection_entry,
    ),
    "xss": VulnClassConfig(
        heading="heading_xss",
        none_found_label="none_xss",
        queue_file="xss_exploitation_queue.json",
        findings_file="xss_findings.md",
        render_entry=render_xss_entry,
    ),
    "auth": VulnClassConfig(
        heading="heading_auth",
        none_found_label="none_auth",
        queue_file="auth_exploitation_queue.json",
        findings_file="auth_findings.md",
        render_entry=render_auth_entry,
    ),
    "authz": VulnClassConfig(
        heading="heading_authz",
        none_found_label="none_authz",
        queue_file="authz_exploitation_queue.json",
        findings_file="authz_findings.md",
        render_entry=render_authz_entry,
    ),
    "ssrf": VulnClassConfig(
        heading="heading_ssrf",
        none_found_label="none_ssrf",
        queue_file="ssrf_exploitation_queue.json",
        findings_file="ssrf_findings.md",
        render_entry=render_ssrf_entry,
    ),
}


def _passes_filter(vuln: Vulnerability, config: ReportConfig) -> bool:
    if config.min_confidence:
        vuln_level = CONFIDENCE_ORDER.get(vuln.confidence, 0)
        min_level = CONFIDENCE_ORDER.get(config.min_confidence, 0)
        if vuln_level < min_level:
            return False
    if config.min_severity:
        severity = getattr(vuln, "severity", None)
        if severity is not None:
            vuln_level = SEVERITY_ORDER.get(severity, 0)
            min_level = SEVERITY_ORDER.get(config.min_severity, 0)
            if vuln_level < min_level:
                return False
    return True


def filter_vulnerabilities(queue: VulnerabilityQueue, config: ReportConfig) -> list[Vulnerability]:
    return [v for v in queue.vulnerabilities if _passes_filter(v, config)]


class FindingsRenderer:
    @staticmethod
    async def render_findings_from_queues(
        deliverables_path: Path,
        report_config: ReportConfig | None = None,
        *,
        queue_subdir: str | None = None,
        findings_subdir: str | None = None,
    ) -> None:
        """Render findings MD from queue JSON.

        Shared by both whitebox and blackbox callers. The two keyword-only params
        route queue READS and findings WRITES to track subdirectories without
        coupling this shared service to either caller's layout:

        - ``findings_subdir``: when set, findings MD is written to
          ``deliverables_path / findings_subdir /`` (created if missing). When
          ``None`` (the whitebox default), findings are written directly under
          ``deliverables_path`` — preserving the pre-2026-07 behaviour so the
          whitebox caller's reads/writes stay inside ``whitebox/``.
        - ``queue_subdir``: when set, queue JSON is read via
          :func:`resolve_track_deliverable` (``deliverables_path / queue_subdir /
          filename`` with legacy root fallback). When ``None``, queues are read
          via :func:`resolve_intermediate` — tiering 后 queue 落桶内
          ``intermediate/``，读侧 intermediate/ 优先 + 平铺老结构兜底。

        Defaults (``None``/``None``) preserve the old single-positional-arg
        behaviour — existing whitebox callers are unaffected.
        """
        config = report_config or ReportConfig()
        if findings_subdir:
            findings_base = deliverables_path / findings_subdir
            findings_base.mkdir(parents=True, exist_ok=True)
        else:
            findings_base = deliverables_path
        for _vuln_class, class_cfg in CLASS_CONFIG.items():
            findings_path = findings_base / class_cfg.findings_file
            if await async_path_exists(findings_path):
                continue
            if queue_subdir:
                queue_path = resolve_track_deliverable(
                    deliverables_path, queue_subdir, class_cfg.queue_file)
            else:
                # tiering（spec 2026-08-18）：queue 是中间产物 → 写侧落桶内
                # intermediate/（executor.py intermediate_path），读侧须
                # intermediate/ 优先 + 平铺老结构兜底（f4b98d38 扫尾模式同口径；
                # 平铺直读会让 findings.md 静默缺失 → assemble 回落
                # analysis_deliverable → 报告页出现分分析报告）。
                queue_path = resolve_intermediate(
                    deliverables_path, class_cfg.queue_file)
            if queue_path is None or not await async_path_exists(queue_path):
                continue

            heading = _M.get(class_cfg.heading)
            try:
                content = await async_read_file(queue_path)
                parsed = VulnerabilityQueue.parse_lenient(
                    content, vuln_class=_vuln_class)
            except Exception as exc:  # noqa: BLE001 — isolate this class
                logger.warning("queue %s unreadable: %s", class_cfg.queue_file, exc)
                await async_write_file(findings_path, "\n".join([
                    f"## {heading}", "",
                    _M.get("queue_unreadable", heading=heading),
                    "", _M.get("disclaimer"), "",
                ]))
                continue

            if parsed.warnings:
                logger.warning(
                    "queue %s parsed leniently: %s", class_cfg.queue_file, parsed.warnings
                )
            queue = parsed.queue
            filtered = filter_vulnerabilities(queue, config)

            sections: list[str] = [f"## {heading}", ""]
            if parsed.warnings:
                sections.append(
                    _M.get("queue_auto_recovered",
                           warnings="; ".join(parsed.warnings),
                           queue_file=class_cfg.queue_file)
                )
                sections.append("")

            if not filtered:
                if parsed.original_form == "object" and not parsed.warnings:
                    sections.append(_M.get(class_cfg.none_found_label))
                else:
                    reason = "; ".join(parsed.warnings) or _M.get("no_parseable_entries")
                    sections.append(
                        _M.get("no_renderable_entries",
                               queue_file=class_cfg.queue_file, reason=reason)
                    )
            else:
                for vuln in filtered:
                    try:
                        sections.append(class_cfg.render_entry(vuln))
                    except Exception as exc:  # noqa: BLE001 — isolate single entry
                        logger.warning(
                            "render entry %s failed: %s",
                            getattr(vuln, "ID", "?"), exc,
                        )
                        sections.append(
                            _M.get("render_error", id=getattr(vuln, "ID", "UNKNOWN"))
                        )

            sections.append("")
            sections.append(_M.get("disclaimer"))
            sections.append("")
            await async_write_file(findings_path, "\n".join(sections))
