"""Route chain builder.

Builds multi-step attack chains by correlating framework-inferred
endpoints with frontend route analysis results.
Ported from /root/shannon/apps/worker/src/services/route-chain-builder.ts
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from supernova_core.i18n import Messages
from supernova_core.services.framework_analyzer import InferredEndpoint
from supernova_core.services.frontend_mapper import FrontendRoute, XssAttackChain

# 攻击链模板双语文案（zh/en 可配，跟随 SUPERNOVA_AGENT_NARRATION_LANG）。
_M = Messages({
    "xss_name": {"zh": "存储型 XSS：{e} -> {r}", "en": "Stored XSS: {e} -> {r}"},
    "xss_desc": {
        "zh": "{e} 的用户输入经 {s} 存储，在 {r} 的 {sink} 处渲染",
        "en": "User input at {e} is stored via {s} and rendered at {r} in {sink}",
    },
    "xss_s1": {"zh": "用户访问 {e} 并提供输入",
               "en": "User navigates to {e} and provides input"},
    "xss_s2": {"zh": "输入经 POST {s} 存储", "en": "Input is stored via POST {s}"},
    "xss_s3": {"zh": "经 GET {s} 读取已存数据",
               "en": "Stored data is retrieved via GET {s}"},
    "xss_s4": {"zh": "数据在 {sink} 处未净化渲染",
               "en": "Data is rendered unsanitized in {sink}"},
    "idor_name": {"zh": "IDOR：{m} {p}（{src}）", "en": "IDOR: {m} {p} ({src})"},
    "idor_desc": {
        "zh": "{m} {p} 由 {src} 自动生成，无归属校验。",
        "en": "{m} {p} is auto-generated by {src} with no ownership validation.",
    },
    "idor_s1": {"zh": "攻击者构造带任意 ID 参数的请求",
                "en": "Attacker crafts request with arbitrary ID parameter"},
    "idor_s2": {"zh": "{m} 无归属校验即触达副作用",
                "en": "{m} reaches side effect without ownership validation"},
})


@dataclass(frozen=True)
class AttackChainStep:
    """A single step in an attack chain."""

    order: int
    phase: str  # 'input' | 'storage' | 'retrieval' | 'render'
    endpoint: str
    method: str
    description: str


@dataclass
class AttackChain:
    """A multi-step attack chain."""

    id: str
    name: str
    description: str
    steps: list[AttackChainStep] = field(default_factory=list)
    vuln_type: str = ""  # 'xss' | 'authz' | 'injection'
    severity: str = "medium"  # 'critical' | 'high' | 'medium' | 'low'
    confidence: str = "theoretical"  # 'confirmed' | 'probable' | 'theoretical'


def build_attack_chains_from_analysis(
    inferred_endpoints: list[InferredEndpoint],
    frontend_routes: list[FrontendRoute],
    xss_chains: list[XssAttackChain],
    logger: logging.Logger,
) -> list[AttackChain]:
    """Build attack chains from framework endpoints and frontend analysis.

    1. XSS chains from frontend analysis (input -> storage -> retrieval -> render)
    2. IDOR chains from framework endpoints without ownership checks
       (correlated with frontend routes that trigger them)
    """
    chains: list[AttackChain] = []

    # 1. Build XSS chains from frontend analysis
    for xss_chain in xss_chains:
        chains.append(
            AttackChain(
                id=f"xss-chain-{len(chains) + 1}",
                name=_M.get("xss_name", e=xss_chain.entry_point, r=xss_chain.render_endpoint),
                description=_M.get("xss_desc", e=xss_chain.entry_point,
                                   s=xss_chain.storage_endpoint,
                                   r=xss_chain.render_endpoint, sink=xss_chain.sink),
                steps=[
                    AttackChainStep(1, "input", xss_chain.entry_point, "GET",
                                    _M.get("xss_s1", e=xss_chain.entry_point)),
                    AttackChainStep(2, "storage", xss_chain.storage_endpoint, "POST",
                                    _M.get("xss_s2", s=xss_chain.storage_endpoint)),
                    AttackChainStep(3, "retrieval", xss_chain.storage_endpoint, "GET",
                                    _M.get("xss_s3", s=xss_chain.storage_endpoint)),
                    AttackChainStep(4, "render", xss_chain.render_endpoint, "GET",
                                    _M.get("xss_s4", sink=xss_chain.sink)),
                ],
                vuln_type="xss",
                severity="high",
                confidence="probable" if xss_chain.confidence == "high" else "theoretical",
            )
        )

    # 2. Build IDOR chains from framework endpoints without ownership checks
    vulnerable_endpoints = [
        ep for ep in inferred_endpoints
        if ":id" in ep.path and ep.vulnerability_indicators
    ]

    for endpoint in vulnerable_endpoints:
        chains.append(
            AttackChain(
                id=f"idor-chain-{len(chains) + 1}",
                name=_M.get("idor_name", m=endpoint.method, p=endpoint.path,
                            src=endpoint.source),
                description=_M.get("idor_desc", m=endpoint.method, p=endpoint.path,
                                   src=endpoint.source),
                steps=[
                    AttackChainStep(1, "input", endpoint.path, endpoint.method,
                                    _M.get("idor_s1")),
                    AttackChainStep(2, "storage", endpoint.path, endpoint.method,
                                    _M.get("idor_s2", m=endpoint.method)),
                ],
                vuln_type="authz",
                severity="high" if endpoint.method == "DELETE" else "medium",
                confidence="probable",
            )
        )

    logger.info("Built %d attack chain(s) from analysis", len(chains))
    return chains
