"""组合扫描融合报告渲染器（spec §10.2）。

按 vuln_class 交叉白盒 queue（``{vt}_exploitation_queue.json``）+ 黑盒 queue，
产 ``deliverables/combined/combined_report.md``：

- 顶部「## 组合摘要」表：每漏洞类一行（白盒发现数 / 黑盒验证数 / 双轨交叉）。
- 「## 按漏洞类详述」：每类一节，白盒视角 + 黑盒视角并列。

对齐粒度 = vuln_class（黑盒本就按 vuln_class 读白盒 queue），不做单个漏洞 1:1。

韧性（spec §10.2 + Task-8 brief）：缺失 / 空 / 不可读 queue 不崩溃 —— 计数兜底 0、
详述 emit「无发现」文案。读 queue 逻辑复用 ``has_valid_whitebox_results`` 口径。
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from supernova_core.i18n import Messages
from supernova_core.utils.paths import (
    BLACKBOX_SUBDIR,
    COMBINED_SUBDIR,
    WHITEBOX_SUBDIR,
    combined_dir,
)

logger = logging.getLogger(__name__)

# spec §10.2：injection/xss/ssrf/authz（不含 auth —— auth 是纯 LLM 轨，黑盒无对应
# finding 可交叉，故不入融合报告；见 CLAUDE.md §1 auth 特殊段）。
_VULN_CLASSES: tuple[str, ...] = ("injection", "xss", "ssrf", "authz")

_COMBINED_REPORT_FILENAME = "combined_report.md"

# 融合报告文案双语（zh/en 可配，跟随 SUPERNOVA_AGENT_NARRATION_LANG）。
_M = Messages({
    "title": {"zh": "# 组合扫描融合报告", "en": "# Combined Scan Fused Report"},
    "summary_h2": {"zh": "## 组合摘要", "en": "## Summary"},
    "detail_h2": {"zh": "## 按漏洞类详述", "en": "## Per-Class Detail"},
    "col_class": {"zh": "漏洞类", "en": "Vulnerability Class"},
    "col_wb": {"zh": "白盒发现", "en": "Whitebox Found"},
    "col_bb": {"zh": "黑盒验证", "en": "Blackbox Verified"},
    "col_cross": {"zh": "双轨交叉", "en": "Cross-Track"},
    "yes": {"zh": "是", "en": "yes"},
    "no": {"zh": "否", "en": "no"},
    "wb_view_h3": {"zh": "### {vt} — 白盒视角（代码证据）",
                   "en": "### {vt} — Whitebox View (Code Evidence)"},
    "bb_view_h3": {"zh": "### {vt} — 黑盒视角（利用验证）",
                   "en": "### {vt} — Blackbox View (Exploit Verification)"},
    "no_findings": {"zh": "_无发现_", "en": "_no findings_"},
    "entry_bullet": {"zh": "- **{id}** {extra}", "en": "- **{id}** {extra}"},
    "generated_note": {
        "zh": "> 本报告由组合扫描自动生成，交叉白盒（代码分析）与黑盒（利用验证）发现。",
        "en": "> Generated by the combined scan; cross-references whitebox (code analysis) "
              "and blackbox (exploit verification) findings.",
    },
})


def _read_queue(queue_path: Path) -> list[dict]:
    """读 {vt}_exploitation_queue.json 的 vulnerabilities 列表。

    韧性：文件缺失 / 损坏 JSON / vulnerabilities 非列表 → 返回空列表（不抛）。
    对齐 ``has_valid_whitebox_results`` 的容错口径。
    """
    if not queue_path.is_file():
        return []
    try:
        data = json.loads(queue_path.read_text("utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError) as exc:
        logger.warning("combined renderer: queue 不可读 %s: %s", queue_path, exc)
        return []
    vulns = data.get("vulnerabilities") if isinstance(data, dict) else None
    if not isinstance(vulns, list):
        return []
    return [v for v in vulns if isinstance(v, dict)]


def _format_entry(vuln: dict) -> str:
    """渲染单条 vuln 为 markdown bullet（用任意可用字段，韧性）。"""
    vid = vuln.get("ID") or vuln.get("id") or "?"
    title = vuln.get("title") or ""
    # 白盒倾向 source/path；黑盒倾向 endpoint。统一拼成可读 extra。
    bits: list[str] = []
    if title:
        bits.append(str(title))
    loc = vuln.get("source") or vuln.get("source_endpoint") or vuln.get("endpoint")
    if loc:
        bits.append(f"@ {loc}")
    path = vuln.get("path")
    if path:
        bits.append(f"→ {path}")
    verdict = vuln.get("verdict")
    if verdict:
        bits.append(f"[{verdict}]")
    extra = " ".join(bits) if bits else ""
    return _M.get("entry_bullet", id=vid, extra=extra)


def render_combined_report(scan_dir: Path) -> Path:
    """生成组合扫描融合报告（spec §10.2）。

    读 ``scan_dir/deliverables/{whitebox,blackbox}/{vt}_exploitation_queue.json``，
    按 ``_VULN_CLASSES`` 交叉，写 ``scan_dir/deliverables/combined/combined_report.md``。

    Args:
        scan_dir: workspace 根（workspaces/<session>），其下 ``deliverables/`` 三桶。

    Returns:
        产物路径（``deliverables/combined/combined_report.md``）。

    韧性：白盒 / 黑盒任一桶缺失、queue 空 / 损坏都不崩溃 —— emit 0 计数 + 无发现。
    """
    deliverables = Path(scan_dir) / "deliverables"
    out_dir = combined_dir(deliverables)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / _COMBINED_REPORT_FILENAME

    wb_base = deliverables / WHITEBOX_SUBDIR
    bb_base = deliverables / BLACKBOX_SUBDIR

    rows: list[tuple[str, int, int]] = []
    detail_sections: list[str] = []

    for vt in _VULN_CLASSES:
        wb_vulns = _read_queue(wb_base / f"{vt}_exploitation_queue.json")
        bb_vulns = _read_queue(bb_base / f"{vt}_exploitation_queue.json")
        rows.append((vt, len(wb_vulns), len(bb_vulns)))

        # 按类详述：白盒视角 + 黑盒视角并列
        wb_block = [_M.get("wb_view_h3", vt=vt), ""]
        if wb_vulns:
            wb_block.extend(_format_entry(v) for v in wb_vulns)
        else:
            wb_block.append(_M.get("no_findings"))
        wb_block.append("")

        bb_block = [_M.get("bb_view_h3", vt=vt), ""]
        if bb_vulns:
            bb_block.extend(_format_entry(v) for v in bb_vulns)
        else:
            bb_block.append(_M.get("no_findings"))
        bb_block.append("")

        detail_sections.append("\n".join(wb_block))
        detail_sections.append("\n".join(bb_block))

    # ── 组装报告 ──────────────────────────────────────────────────────────
    lines: list[str] = [_M.get("title"), "", _M.get("generated_note"), "",
                        _M.get("summary_h2"), ""]

    # 摘要表
    lines.append(f"| {_M.get('col_class')} | {_M.get('col_wb')} | "
                 f"{_M.get('col_bb')} | {_M.get('col_cross')} |")
    lines.append("|---|---|---|---|")
    for vt, wb_n, bb_n in rows:
        cross = _M.get("yes") if (wb_n > 0 and bb_n > 0) else _M.get("no")
        lines.append(f"| {vt} | {wb_n} | {bb_n} | {cross} |")
    lines.append("")

    # 按类详述
    lines.append(_M.get("detail_h2"))
    lines.append("")
    lines.append("\n".join(detail_sections))

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
