"""组合扫描融合报告渲染器（spec §10.2）。

按 vuln_class 交叉白盒 queue + 黑盒 verdicts，产
``deliverables/combined/combined_report.md``：

- 顶部「## 组合摘要」表：每漏洞类一行（白盒发现数 / 黑盒验证数 / 双轨交叉）。
- 「## 按漏洞类详述」：每类一节（### {vt}），白盒视角（####）+ 黑盒视角（####）并列。

双轨读不同产物（与 ``workspace.get_workspace_vuln_counts`` 同口径）：
- 白盒：``{vt}_exploitation_queue.json``，count = ``len(vulnerabilities)``。
- 黑盒：``{vt}_exploit_verdicts.json``，count = ``verdicts`` 中 ``status=="exploited"`` 的条目数
  （成功 exploit 数；见 ``workspace.py:127-160``、``executor.py:221``、
  ``exploitation_checker.py:222``）。

对齐粒度 = vuln_class（黑盒本就按 vuln_class 读白盒 queue），不做单个漏洞 1:1。

韧性（spec §10.2 + Task-8 brief）：缺失 / 空 / 不可读产物不崩溃 —— 计数兜底 0、
详述 emit「无发现」文案。
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

from supernova_core.i18n import Messages

logger = logging.getLogger(__name__)

# spec §10.2：injection/xss/ssrf/authz（不含 auth —— auth 是纯 LLM 轨，黑盒无对应
# finding 可交叉，故不入融合报告；见 CLAUDE.md §1 auth 特殊段）。
_VULN_CLASSES: tuple[str, ...] = ("injection", "xss", "ssrf", "authz")

# 黑盒 verdict status 枚举（见 collectors/exploit.py::_SINGLE_VERDICT_SCHEMA），
# status=="exploited" 计为「黑盒验证」（成功 exploit），其余为尝试但未利用。
_VERDICT_EXPLOITED = "exploited"

_COMBINED_REPORT_FILENAME = "combined_report.md"

# 融合报告文案双语（zh/en 可配，跟随 SUPERNOVA_AGENT_NARRATION_LANG）。
_M = Messages({
    "title": {"zh": "# 组合扫描融合报告", "en": "# Combined Scan Fused Report"},
    "summary_h2": {"zh": "## 组合摘要", "en": "## Summary"},
    "detail_h2": {"zh": "## 按漏洞类详述", "en": "## Per-Class Detail"},
    "col_class": {"zh": "漏洞类", "en": "Vulnerability Class"},
    "col_wb": {"zh": "白盒发现", "en": "Whitebox Found"},
    "col_bb": {"zh": "黑盒验证", "en": "Blackbox Verified"},
    "col_cross": {"zh": "双轨交叉", "en": "Cross-Track"},
    "yes": {"zh": "是", "en": "yes"},
    "no": {"zh": "否", "en": "no"},
    # 按类详述标题层级（spec §10.2）：### {vt} → #### 白盒视角 / #### 黑盒视角
    "wb_view_h4": {"zh": "#### 白盒视角（代码证据）",
                   "en": "#### Whitebox View (Code Evidence)"},
    "bb_view_h4": {"zh": "#### 黑盒视角（利用验证）",
                   "en": "#### Blackbox View (Exploit Verification)"},
    "no_findings": {"zh": "_无发现_", "en": "_no findings_"},
    "wb_entry_bullet": {"zh": "- **{id}** {extra}", "en": "- **{id}** {extra}"},
    "bb_entry_bullet": {"zh": "- **{id}** {extra}", "en": "- **{id}** {extra}"},
    "generated_note": {
        "zh": "> 本报告由组合扫描自动生成，交叉白盒（代码分析）与黑盒（利用验证）发现。",
        "en": "> Generated by the combined scan; cross-references whitebox (code analysis) "
              "and blackbox (exploit verification) findings.",
    },
})


def _read_queue(queue_path: Path) -> list[dict]:
    """读白盒 ``{vt}_exploitation_queue.json`` 的 vulnerabilities 列表。

    韧性：文件缺失 / 损坏 JSON / vulnerabilities 非列表 → 返回空列表（不抛）。
    对齐 ``has_valid_whitebox_results`` 的容错口径。
    """
    if not queue_path.is_file():
        return []
    try:
        data = json.loads(queue_path.read_text("utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError) as exc:
        logger.warning("combined renderer: whitebox queue 不可读 %s: %s", queue_path, exc)
        return []
    vulns = data.get("vulnerabilities") if isinstance(data, dict) else None
    if not isinstance(vulns, list):
        return []
    return [v for v in vulns if isinstance(v, dict)]


def _read_verdicts(verdicts_path: Path) -> list[dict]:
    """读黑盒 ``{vt}_exploit_verdicts.json`` 的 verdicts 列表。

    与白盒 queue 不同 stem（见 ``workspace.py:127-160``、``executor.py:221``）：
    黑盒 exploit agent 写 ``{vc}_exploit_verdicts.json``，schema =
    ``{vuln_class, accepted_ids, verdicts, rejected}``，``verdicts`` 每条含
    ``vulnerability_id`` / ``status`` (exploited|blocked_by_security|...)。

    返回全部 accepted verdict 条目（不在此过滤 status —— 计数由调用方按
    ``status=="exploited"`` 做，详述可展示非 exploited 的 blocked/potential 上下文）。

    韧性：文件缺失 / 损坏 JSON / verdicts 非列表 → 返回空列表（不抛）。
    """
    if not verdicts_path.is_file():
        return []
    try:
        data = json.loads(verdicts_path.read_text("utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError, UnicodeDecodeError) as exc:
        logger.warning("combined renderer: blackbox verdicts 不可读 %s: %s", verdicts_path, exc)
        return []
    verdicts = data.get("verdicts") if isinstance(data, dict) else None
    if not isinstance(verdicts, list):
        return []
    return [v for v in verdicts if isinstance(v, dict)]


def _count_exploited(verdicts: list[dict]) -> int:
    """数 ``status=="exploited"`` 的 verdict 条目（成功 exploit 数）。

    与 ``workspace.get_workspace_vuln_counts`` 黑盒计数口径一致。
    """
    return sum(1 for v in verdicts if v.get("status") == _VERDICT_EXPLOITED)


def _format_queue_entry(vuln: dict) -> str:
    """渲染单条白盒 queue 条目为 markdown bullet（用任意可用字段，韧性）。"""
    vid = vuln.get("ID") or vuln.get("id") or "?"
    bits: list[str] = []
    title = vuln.get("title")
    if title:
        bits.append(str(title))
    loc = vuln.get("source") or vuln.get("source_endpoint")
    if loc:
        bits.append(f"@ {loc}")
    path = vuln.get("path")
    if path:
        bits.append(f"→ {path}")
    extra = " ".join(bits) if bits else ""
    return _M.get("wb_entry_bullet", id=vid, extra=extra)


def _format_verdict_entry(verdict: dict) -> str:
    """渲染单条黑盒 verdict 为 markdown bullet。

    verdict schema（见 ``collectors/exploit.py``）：``vulnerability_id`` / ``status``
    / ``severity`` / ``impact`` / ``exploitation_steps`` / ``proof_of_impact``。
    与白盒 queue 条目字段不同（无 source/path），用 verdict 字段格式化。
    """
    vid = verdict.get("vulnerability_id") or verdict.get("id") or "?"
    status = verdict.get("status", "?")
    bits: list[str] = [f"[{status}]"]
    severity = verdict.get("severity")
    if severity:
        bits.append(str(severity))
    impact = verdict.get("impact")
    if impact:
        bits.append(str(impact))
    extra = " ".join(bits)
    return _M.get("bb_entry_bullet", id=vid, extra=extra)


def render_combined_report(*, whitebox_root: Path, blackbox_root: Path,
                           out_dir: Path) -> Path:
    """生成 per-run 融合报告（spec §9/§10.2）。

    双路径签名（T4）：读 ``whitebox_root/{vt}_exploitation_queue.json`` +
    ``blackbox_root/{vt}_exploit_verdicts.json``，按 ``_VULN_CLASSES`` 交叉，写
    ``out_dir/combined_report.md``。

    Args:
        whitebox_root: 白盒产物根（``<wb>/deliverables/whitebox/``）。
        blackbox_root: 黑盒产物根（``<wb>/blackbox-runs/run-K/deliverables/blackbox/``）。
        out_dir: 输出根（``<wb>/combined/run-K/``）。

    Returns:
        产物路径（``out_dir/combined_report.md``）。

    韧性：白盒 / 黑盒任一根缺失、产物空 / 损坏都不崩溃 —— emit 0 计数 + 无发现。
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / _COMBINED_REPORT_FILENAME

    wb_base = Path(whitebox_root)
    bb_base = Path(blackbox_root)

    rows: list[tuple[str, int, int]] = []
    detail_sections: list[str] = []

    for vt in _VULN_CLASSES:
        wb_vulns = _read_queue(wb_base / f"{vt}_exploitation_queue.json")
        bb_verdicts = _read_verdicts(bb_base / f"{vt}_exploit_verdicts.json")
        bb_exploited = _count_exploited(bb_verdicts)
        rows.append((vt, len(wb_vulns), bb_exploited))

        # ── ### {vt} ──────────────────────────────────────────────────────
        class_block: list[str] = [f"### {vt}", ""]

        # #### 白盒视角（代码证据）
        class_block.append(_M.get("wb_view_h4"))
        class_block.append("")
        if wb_vulns:
            class_block.extend(_format_queue_entry(v) for v in wb_vulns)
        else:
            class_block.append(_M.get("no_findings"))
        class_block.append("")

        # #### 黑盒视角（利用验证）
        class_block.append(_M.get("bb_view_h4"))
        class_block.append("")
        if bb_verdicts:
            class_block.extend(_format_verdict_entry(v) for v in bb_verdicts)
        else:
            class_block.append(_M.get("no_findings"))
        class_block.append("")

        detail_sections.append("\n".join(class_block))

    # ── 组装报告 ──────────────────────────────────────────────────────────
    lines: list[str] = [_M.get("title"), "", _M.get("generated_note"), "",
                        _M.get("summary_h2"), ""]

    # 摘要表
    lines.append(f"| {_M.get('col_class')} | {_M.get('col_wb')} | "
                 f"{_M.get('col_bb')} | {_M.get('col_cross')} |")
    lines.append("|---|---|---|---|")
    for vt, wb_n, bb_n in rows:
        cross = _M.get("yes") if (wb_n > 0 and bb_n > 0) else _M.get("no")
        lines.append(f"| {vt} | {wb_n} | {bb_n} | {cross} |")
    lines.append("")

    # 按类详述
    lines.append(_M.get("detail_h2"))
    lines.append("")
    lines.append("\n".join(detail_sections))

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
