// Copyright (C) 2025 Keygraph, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.

/**
 * Route chain builder
 *
 * Builds multi-step attack chains by correlating framework-inferred
 * endpoints with frontend route analysis results. Produces structured
 * attack scenarios for downstream exploitation agents.
 */

import type { ActivityLogger } from '../types/activity-logger.js';
import type { InferredEndpoint } from './framework-analyzer.js';
import type { FrontendRoute, XssAttackChain } from './frontend-mapper.js';

export interface AttackChainStep {
  order: number;
  phase: 'input' | 'storage' | 'retrieval' | 'render';
  endpoint: string;
  method: string;
  description: string;
}

export interface AttackChain {
  id: string;
  name: string;
  description: string;
  steps: readonly AttackChainStep[];
  vulnType: 'xss' | 'authz' | 'injection';
  severity: 'critical' | 'high' | 'medium' | 'low';
  confidence: 'confirmed' | 'probable' | 'theoretical';
}

/**
 * Build attack chains from framework endpoints and frontend analysis.
 * Correlates auto-generated endpoints with frontend routes to identify
 * complete attack paths.
 */
export function buildAttackChainsFromAnalysis(
  inferredEndpoints: readonly InferredEndpoint[],
  frontendRoutes: readonly FrontendRoute[],
  xssChains: readonly XssAttackChain[],
  logger: ActivityLogger,
): AttackChain[] {
  const chains: AttackChain[] = [];

  // 1. Build XSS chains from frontend analysis
  for (const xssChain of xssChains) {
    chains.push({
      id: `xss-chain-${chains.length + 1}`,
      name: `Stored XSS: ${xssChain.entryPoint} → ${xssChain.renderEndpoint}`,
      description: `User input at ${xssChain.entryPoint} is stored via ${xssChain.storageEndpoint} and rendered at ${xssChain.renderEndpoint} in ${xssChain.sink}`,
      steps: [
        {
          order: 1,
          phase: 'input',
          endpoint: xssChain.entryPoint,
          method: 'GET',
          description: `User navigates to ${xssChain.entryPoint} and provides input`,
        },
        {
          order: 2,
          phase: 'storage',
          endpoint: xssChain.storageEndpoint,
          method: 'POST',
          description: `Input is stored via POST ${xssChain.storageEndpoint}`,
        },
        {
          order: 3,
          phase: 'retrieval',
          endpoint: xssChain.storageEndpoint,
          method: 'GET',
          description: `Stored data is retrieved via GET ${xssChain.storageEndpoint}`,
        },
        {
          order: 4,
          phase: 'render',
          endpoint: xssChain.renderEndpoint,
          method: 'GET',
          description: `Data is rendered unsanitized in ${xssChain.sink}`,
        },
      ],
      vulnType: 'xss',
      severity: 'high',
      confidence: xssChain.confidence === 'high' ? 'probable' : 'theoretical',
    });
  }

  // 2. Build IDOR chains from framework endpoints without ownership checks
  const vulnerableEndpoints = inferredEndpoints.filter(
    (ep) => ep.path.includes(':id') && ep.vulnerabilityIndicators.length > 0,
  );

  for (const endpoint of vulnerableEndpoints) {
    // Check if this endpoint has any frontend route that triggers it
    const relatedRoute = frontendRoutes.find((r) =>
      r.apiCalls.some((a) => endpoint.path.startsWith(extractPathPrefix(a.endpoint))),
    );

    chains.push({
      id: `idor-chain-${chains.length + 1}`,
      name: `IDOR: ${endpoint.method} ${endpoint.path} (${endpoint.source})`,
      description: `${endpoint.method} ${endpoint.path} is auto-generated by ${endpoint.source} with no ownership validation. ${relatedRoute ? `Triggered from frontend route ${relatedRoute.path}.` : ''}`,
      steps: [
        {
          order: 1,
          phase: 'input',
          endpoint: endpoint.path,
          method: endpoint.method,
          description: `Attacker crafts request with arbitrary ID parameter`,
        },
        {
          order: 2,
          phase: 'storage',
          endpoint: endpoint.path,
          method: endpoint.method,
          description: `${endpoint.method} reaches side effect without ownership validation`,
        },
      ],
      vulnType: 'authz',
      severity: endpoint.method === 'DELETE' ? 'high' : 'medium',
      confidence: 'probable',
    });
  }

  logger.info(`Built ${chains.length} attack chain(s) from analysis`);
  return chains;
}

/**
 * Extract path prefix for correlation (e.g., /api/Users from /api/Users/:id).
 */
function extractPathPrefix(endpoint: string): string {
  const parts = endpoint.split('/');
  return parts.filter((p) => !p.startsWith(':')).join('/');
}
