import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from shannon_core.models.config import ReportConfig
from shannon_core.models.queue_schemas import (
    AuthVulnerability,
    AuthzVulnerability,
    InjectionVulnerability,
    SsrfVulnerability,
    Vulnerability,
    VulnerabilityQueue,
    XssVulnerability,
)
from shannon_core.utils.file_io import async_path_exists, async_read_file, async_write_file
from shannon_core.utils.paths import resolve_track_deliverable

logger = logging.getLogger(__name__)

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}
CONFIDENCE_ORDER = {"low": 0, "medium": 1, "high": 2}

DISCLAIMER = (
    "> **Disclaimer:** This report was generated by an automated security assessment tool. "
    "All findings should be verified by a qualified security professional before taking action."
)


@dataclass
class VulnClassConfig:
    heading: str
    none_found_label: str
    queue_file: str
    findings_file: str
    render_entry: Callable


def render_injection_entry(vuln: InjectionVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"- **Vulnerable Location:** {location}")
    if vuln.sink_call:
        lines.append(f"- **Sink Call:** {vuln.sink_call}")
    if vuln.concat_occurrences:
        lines.append(f"- **Concat Occurrences:** {vuln.concat_occurrences}")
    if vuln.sanitization_observed:
        lines.append(f"- **Sanitization Observed:** {vuln.sanitization_observed}")
    if vuln.verdict:
        lines.append(f"- **Verdict:** {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"- **Witness Payload:** {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_xss_entry(vuln: XssVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"- **Vulnerable Location:** {location}")
    if vuln.sink_function:
        lines.append(f"- **Sink Function:** {vuln.sink_function}")
    if vuln.render_context:
        lines.append(f"- **Render Context:** {vuln.render_context}")
    if vuln.encoding_observed:
        lines.append(f"- **Encoding Observed:** {vuln.encoding_observed}")
    if vuln.verdict:
        lines.append(f"- **Verdict:** {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"- **Witness Payload:** {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_auth_entry(vuln: AuthVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source_endpoint:
        lines.append(f"- **Source Endpoint:** {vuln.source_endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"- **Missing Defense:** {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"- **Exploitation Hypothesis:** {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"- **Suggested Exploit Technique:** {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_authz_entry(vuln: AuthzVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.endpoint:
        lines.append(f"- **Endpoint:** {vuln.endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.role_context:
        lines.append(f"- **Role Context:** {vuln.role_context}")
    if vuln.guard_evidence:
        lines.append(f"- **Guard Evidence:** {vuln.guard_evidence}")
    if vuln.side_effect:
        lines.append(f"- **Side Effect:** {vuln.side_effect}")
    if vuln.reason:
        lines.append(f"- **Reason:** {vuln.reason}")
    if vuln.minimal_witness:
        lines.append(f"- **Minimal Witness:** {vuln.minimal_witness}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_ssrf_entry(vuln: SsrfVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source_endpoint:
        lines.append(f"- **Source Endpoint:** {vuln.source_endpoint}")
    if vuln.vulnerable_parameter:
        lines.append(f"- **Vulnerable Parameter:** {vuln.vulnerable_parameter}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"- **Missing Defense:** {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"- **Exploitation Hypothesis:** {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"- **Suggested Exploit Technique:** {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)




CLASS_CONFIG: dict[str, VulnClassConfig] = {
    "injection": VulnClassConfig(
        heading="Injection Vulnerabilities",
        none_found_label="No injection vulnerabilities found.",
        queue_file="injection_exploitation_queue.json",
        findings_file="injection_findings.md",
        render_entry=render_injection_entry,
    ),
    "xss": VulnClassConfig(
        heading="Cross-Site Scripting (XSS)",
        none_found_label="No XSS vulnerabilities found.",
        queue_file="xss_exploitation_queue.json",
        findings_file="xss_findings.md",
        render_entry=render_xss_entry,
    ),
    "auth": VulnClassConfig(
        heading="Authentication Vulnerabilities",
        none_found_label="No authentication vulnerabilities found.",
        queue_file="auth_exploitation_queue.json",
        findings_file="auth_findings.md",
        render_entry=render_auth_entry,
    ),
    "authz": VulnClassConfig(
        heading="Authorization Vulnerabilities",
        none_found_label="No authorization vulnerabilities found.",
        queue_file="authz_exploitation_queue.json",
        findings_file="authz_findings.md",
        render_entry=render_authz_entry,
    ),
    "ssrf": VulnClassConfig(
        heading="Server-Side Request Forgery (SSRF)",
        none_found_label="No SSRF vulnerabilities found.",
        queue_file="ssrf_exploitation_queue.json",
        findings_file="ssrf_findings.md",
        render_entry=render_ssrf_entry,
    ),
}


def _passes_filter(vuln: Vulnerability, config: ReportConfig) -> bool:
    if config.min_confidence:
        vuln_level = CONFIDENCE_ORDER.get(vuln.confidence, 0)
        min_level = CONFIDENCE_ORDER.get(config.min_confidence, 0)
        if vuln_level < min_level:
            return False
    if config.min_severity:
        severity = getattr(vuln, "severity", None)
        if severity is not None:
            vuln_level = SEVERITY_ORDER.get(severity, 0)
            min_level = SEVERITY_ORDER.get(config.min_severity, 0)
            if vuln_level < min_level:
                return False
    return True


def filter_vulnerabilities(queue: VulnerabilityQueue, config: ReportConfig) -> list[Vulnerability]:
    return [v for v in queue.vulnerabilities if _passes_filter(v, config)]


class FindingsRenderer:
    @staticmethod
    async def render_findings_from_queues(
        deliverables_path: Path,
        report_config: ReportConfig | None = None,
        *,
        queue_subdir: str | None = None,
        findings_subdir: str | None = None,
    ) -> None:
        """Render findings MD from queue JSON.

        Shared by both whitebox and blackbox callers. The two keyword-only params
        route queue READS and findings WRITES to track subdirectories without
        coupling this shared service to either caller's layout:

        - ``findings_subdir``: when set, findings MD is written to
          ``deliverables_path / findings_subdir /`` (created if missing). When
          ``None`` (the whitebox default), findings are written directly under
          ``deliverables_path`` — preserving the pre-2026-07 behaviour so the
          whitebox caller's reads/writes stay inside ``whitebox/``.
        - ``queue_subdir``: when set, queue JSON is read via
          :func:`resolve_track_deliverable` (``deliverables_path / queue_subdir /
          filename`` with legacy root fallback). When ``None``, queues are read
          directly under ``deliverables_path``.

        Defaults (``None``/``None``) preserve the old single-positional-arg
        behaviour — existing whitebox callers are unaffected.
        """
        config = report_config or ReportConfig()
        if findings_subdir:
            findings_base = deliverables_path / findings_subdir
            findings_base.mkdir(parents=True, exist_ok=True)
        else:
            findings_base = deliverables_path
        for _vuln_class, class_cfg in CLASS_CONFIG.items():
            findings_path = findings_base / class_cfg.findings_file
            if await async_path_exists(findings_path):
                continue
            if queue_subdir:
                queue_path = resolve_track_deliverable(
                    deliverables_path, queue_subdir, class_cfg.queue_file)
            else:
                queue_path = deliverables_path / class_cfg.queue_file
            if not await async_path_exists(queue_path):
                continue

            try:
                content = await async_read_file(queue_path)
                parsed = VulnerabilityQueue.parse_lenient(content)
            except Exception as exc:  # noqa: BLE001 — isolate this class
                logger.warning("queue %s unreadable: %s", class_cfg.queue_file, exc)
                await async_write_file(findings_path, "\n".join([
                    f"## {class_cfg.heading}", "",
                    f"> ⚠️ {class_cfg.heading} queue unreadable; findings unavailable for this class. See logs.",
                    "", DISCLAIMER, "",
                ]))
                continue

            if parsed.warnings:
                logger.warning(
                    "queue %s parsed leniently: %s", class_cfg.queue_file, parsed.warnings
                )
            queue = parsed.queue
            filtered = filter_vulnerabilities(queue, config)

            sections: list[str] = [f"## {class_cfg.heading}", ""]
            if parsed.warnings:
                sections.append(
                    "> ⚠️ Queue auto-recovered ("
                    + "; ".join(parsed.warnings)
                    + f"). Raw queue preserved at `{class_cfg.queue_file}`; verify data integrity."
                )
                sections.append("")

            if not filtered:
                if parsed.original_form == "object" and not parsed.warnings:
                    sections.append(class_cfg.none_found_label)
                else:
                    reason = "; ".join(parsed.warnings) or "no parseable entries"
                    sections.append(
                        f"> ⚠️ No renderable entries in `{class_cfg.queue_file}` ({reason})."
                    )
            else:
                for vuln in filtered:
                    try:
                        sections.append(class_cfg.render_entry(vuln))
                    except Exception as exc:  # noqa: BLE001 — isolate single entry
                        logger.warning(
                            "render entry %s failed: %s",
                            getattr(vuln, "ID", "?"), exc,
                        )
                        sections.append(
                            f"### {getattr(vuln, 'ID', 'UNKNOWN')} — render error\n"
                        )

            sections.append("")
            sections.append(DISCLAIMER)
            sections.append("")
            await async_write_file(findings_path, "\n".join(sections))
