from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from shannon_core.models.config import ReportConfig
from shannon_core.models.queue_schemas import (
    AuthVulnerability,
    AuthzVulnerability,
    InjectionVulnerability,
    MisconfigVulnerability,
    SsrfVulnerability,
    Vulnerability,
    VulnerabilityQueue,
    XssVulnerability,
)
from shannon_core.utils.file_io import async_path_exists, async_read_file, async_write_file

SEVERITY_ORDER = {"low": 0, "medium": 1, "high": 2, "critical": 3}
CONFIDENCE_ORDER = {"low": 0, "medium": 1, "high": 2}

DISCLAIMER = (
    "> **Disclaimer:** This report was generated by an automated security assessment tool. "
    "All findings should be verified by a qualified security professional before taking action."
)


@dataclass
class VulnClassConfig:
    heading: str
    none_found_label: str
    queue_file: str
    findings_file: str
    render_entry: Callable


def render_injection_entry(vuln: InjectionVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"- **Vulnerable Location:** {location}")
    if vuln.sink_call:
        lines.append(f"- **Sink Call:** {vuln.sink_call}")
    if vuln.concat_occurrences:
        lines.append(f"- **Concat Occurrences:** {vuln.concat_occurrences}")
    if vuln.sanitization_observed:
        lines.append(f"- **Sanitization Observed:** {vuln.sanitization_observed}")
    if vuln.verdict:
        lines.append(f"- **Verdict:** {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"- **Witness Payload:** {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_xss_entry(vuln: XssVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source or vuln.path:
        location = f"{vuln.source or 'N/A'} → {vuln.path or 'N/A'}"
        lines.append(f"- **Vulnerable Location:** {location}")
    if vuln.sink_function:
        lines.append(f"- **Sink Function:** {vuln.sink_function}")
    if vuln.render_context:
        lines.append(f"- **Render Context:** {vuln.render_context}")
    if vuln.encoding_observed:
        lines.append(f"- **Encoding Observed:** {vuln.encoding_observed}")
    if vuln.verdict:
        lines.append(f"- **Verdict:** {vuln.verdict}")
    if vuln.witness_payload:
        lines.append(f"- **Witness Payload:** {vuln.witness_payload}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_auth_entry(vuln: AuthVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source_endpoint:
        lines.append(f"- **Source Endpoint:** {vuln.source_endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"- **Missing Defense:** {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"- **Exploitation Hypothesis:** {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"- **Suggested Exploit Technique:** {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_authz_entry(vuln: AuthzVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.endpoint:
        lines.append(f"- **Endpoint:** {vuln.endpoint}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.role_context:
        lines.append(f"- **Role Context:** {vuln.role_context}")
    if vuln.guard_evidence:
        lines.append(f"- **Guard Evidence:** {vuln.guard_evidence}")
    if vuln.side_effect:
        lines.append(f"- **Side Effect:** {vuln.side_effect}")
    if vuln.reason:
        lines.append(f"- **Reason:** {vuln.reason}")
    if vuln.minimal_witness:
        lines.append(f"- **Minimal Witness:** {vuln.minimal_witness}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_ssrf_entry(vuln: SsrfVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source_endpoint:
        lines.append(f"- **Source Endpoint:** {vuln.source_endpoint}")
    if vuln.vulnerable_parameter:
        lines.append(f"- **Vulnerable Parameter:** {vuln.vulnerable_parameter}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"- **Missing Defense:** {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"- **Exploitation Hypothesis:** {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"- **Suggested Exploit Technique:** {vuln.suggested_exploit_technique}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


def render_misconfig_entry(vuln: MisconfigVulnerability) -> str:
    lines = [f"### {vuln.ID}", "", "**Summary:**"]
    if vuln.source_endpoint:
        lines.append(f"- **Source Endpoint:** {vuln.source_endpoint}")
    if vuln.vulnerable_parameter:
        lines.append(f"- **Vulnerable Parameter:** {vuln.vulnerable_parameter}")
    if vuln.vulnerable_code_location:
        lines.append(f"- **Vulnerable Code Location:** {vuln.vulnerable_code_location}")
    if vuln.missing_defense:
        lines.append(f"- **Missing Defense:** {vuln.missing_defense}")
    if vuln.exploitation_hypothesis:
        lines.append(f"- **Exploitation Hypothesis:** {vuln.exploitation_hypothesis}")
    if vuln.suggested_exploit_technique:
        lines.append(f"- **Suggested Exploit Technique:** {vuln.suggested_exploit_technique}")
    if vuln.redirect_sink:
        lines.append(f"- **Redirect Sink:** {vuln.redirect_sink}")
    if vuln.existing_validation:
        lines.append(f"- **Existing Validation:** {vuln.existing_validation}")
    if vuln.notes:
        lines.append(f"\n**Notes:** {vuln.notes}")
    lines.append("")
    return "\n".join(lines)


CLASS_CONFIG: dict[str, VulnClassConfig] = {
    "injection": VulnClassConfig(
        heading="Injection Vulnerabilities",
        none_found_label="No injection vulnerabilities found.",
        queue_file="injection_exploitation_queue.json",
        findings_file="injection_findings.md",
        render_entry=render_injection_entry,
    ),
    "xss": VulnClassConfig(
        heading="Cross-Site Scripting (XSS)",
        none_found_label="No XSS vulnerabilities found.",
        queue_file="xss_exploitation_queue.json",
        findings_file="xss_findings.md",
        render_entry=render_xss_entry,
    ),
    "auth": VulnClassConfig(
        heading="Authentication Vulnerabilities",
        none_found_label="No authentication vulnerabilities found.",
        queue_file="auth_exploitation_queue.json",
        findings_file="auth_findings.md",
        render_entry=render_auth_entry,
    ),
    "authz": VulnClassConfig(
        heading="Authorization Vulnerabilities",
        none_found_label="No authorization vulnerabilities found.",
        queue_file="authz_exploitation_queue.json",
        findings_file="authz_findings.md",
        render_entry=render_authz_entry,
    ),
    "ssrf": VulnClassConfig(
        heading="Server-Side Request Forgery (SSRF)",
        none_found_label="No SSRF vulnerabilities found.",
        queue_file="ssrf_exploitation_queue.json",
        findings_file="ssrf_findings.md",
        render_entry=render_ssrf_entry,
    ),
    "misconfig": VulnClassConfig(
        heading="Security Misconfigurations",
        none_found_label="No security misconfigurations found.",
        queue_file="misconfig_exploitation_queue.json",
        findings_file="misconfig_findings.md",
        render_entry=render_misconfig_entry,
    ),
}


def _passes_filter(vuln: Vulnerability, config: ReportConfig) -> bool:
    if config.min_confidence:
        vuln_level = CONFIDENCE_ORDER.get(vuln.confidence, 0)
        min_level = CONFIDENCE_ORDER.get(config.min_confidence, 0)
        if vuln_level < min_level:
            return False
    if config.min_severity:
        severity = getattr(vuln, "severity", None)
        if severity is not None:
            vuln_level = SEVERITY_ORDER.get(severity, 0)
            min_level = SEVERITY_ORDER.get(config.min_severity, 0)
            if vuln_level < min_level:
                return False
    return True


def filter_vulnerabilities(queue: VulnerabilityQueue, config: ReportConfig) -> list[Vulnerability]:
    return [v for v in queue.vulnerabilities if _passes_filter(v, config)]


class FindingsRenderer:
    @staticmethod
    async def render_findings_from_queues(
        deliverables_path: Path,
        report_config: ReportConfig | None = None,
    ) -> None:
        config = report_config or ReportConfig()
        for _vuln_class, class_cfg in CLASS_CONFIG.items():
            findings_path = deliverables_path / class_cfg.findings_file
            if await async_path_exists(findings_path):
                continue
            queue_path = deliverables_path / class_cfg.queue_file
            if not await async_path_exists(queue_path):
                continue

            content = await async_read_file(queue_path)
            queue = VulnerabilityQueue.model_validate_json(content)
            filtered = filter_vulnerabilities(queue, config)

            sections: list[str] = [f"## {class_cfg.heading}", ""]
            if not filtered:
                sections.append(class_cfg.none_found_label)
            else:
                for vuln in filtered:
                    sections.append(class_cfg.render_entry(vuln))

            sections.append("")
            sections.append(DISCLAIMER)
            sections.append("")
            await async_write_file(findings_path, "\n".join(sections))
