"""Route chain builder.

Builds multi-step attack chains by correlating framework-inferred
endpoints with frontend route analysis results.
Ported from /root/shannon/apps/worker/src/services/route-chain-builder.ts
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from shannon_core.services.framework_analyzer import InferredEndpoint
from shannon_core.services.frontend_mapper import FrontendRoute, XssAttackChain


@dataclass(frozen=True)
class AttackChainStep:
    """A single step in an attack chain."""

    order: int
    phase: str  # 'input' | 'storage' | 'retrieval' | 'render'
    endpoint: str
    method: str
    description: str


@dataclass
class AttackChain:
    """A multi-step attack chain."""

    id: str
    name: str
    description: str
    steps: list[AttackChainStep] = field(default_factory=list)
    vuln_type: str = ""  # 'xss' | 'authz' | 'injection'
    severity: str = "medium"  # 'critical' | 'high' | 'medium' | 'low'
    confidence: str = "theoretical"  # 'confirmed' | 'probable' | 'theoretical'


def build_attack_chains_from_analysis(
    inferred_endpoints: list[InferredEndpoint],
    frontend_routes: list[FrontendRoute],
    xss_chains: list[XssAttackChain],
    logger: logging.Logger,
) -> list[AttackChain]:
    """Build attack chains from framework endpoints and frontend analysis.

    1. XSS chains from frontend analysis (input -> storage -> retrieval -> render)
    2. IDOR chains from framework endpoints without ownership checks
       (correlated with frontend routes that trigger them)
    """
    chains: list[AttackChain] = []

    # 1. Build XSS chains from frontend analysis
    for xss_chain in xss_chains:
        chains.append(
            AttackChain(
                id=f"xss-chain-{len(chains) + 1}",
                name=f"Stored XSS: {xss_chain.entry_point} -> {xss_chain.render_endpoint}",
                description=(
                    f"User input at {xss_chain.entry_point} is stored via "
                    f"{xss_chain.storage_endpoint} and rendered at "
                    f"{xss_chain.render_endpoint} in {xss_chain.sink}"
                ),
                steps=[
                    AttackChainStep(1, "input", xss_chain.entry_point, "GET",
                                    f"User navigates to {xss_chain.entry_point} and provides input"),
                    AttackChainStep(2, "storage", xss_chain.storage_endpoint, "POST",
                                    f"Input is stored via POST {xss_chain.storage_endpoint}"),
                    AttackChainStep(3, "retrieval", xss_chain.storage_endpoint, "GET",
                                    f"Stored data is retrieved via GET {xss_chain.storage_endpoint}"),
                    AttackChainStep(4, "render", xss_chain.render_endpoint, "GET",
                                    f"Data is rendered unsanitized in {xss_chain.sink}"),
                ],
                vuln_type="xss",
                severity="high",
                confidence="probable" if xss_chain.confidence == "high" else "theoretical",
            )
        )

    # 2. Build IDOR chains from framework endpoints without ownership checks
    vulnerable_endpoints = [
        ep for ep in inferred_endpoints
        if ":id" in ep.path and ep.vulnerability_indicators
    ]

    for endpoint in vulnerable_endpoints:
        chains.append(
            AttackChain(
                id=f"idor-chain-{len(chains) + 1}",
                name=f"IDOR: {endpoint.method} {endpoint.path} ({endpoint.source})",
                description=(
                    f"{endpoint.method} {endpoint.path} is auto-generated by "
                    f"{endpoint.source} with no ownership validation."
                ),
                steps=[
                    AttackChainStep(1, "input", endpoint.path, endpoint.method,
                                    "Attacker crafts request with arbitrary ID parameter"),
                    AttackChainStep(2, "storage", endpoint.path, endpoint.method,
                                    f"{endpoint.method} reaches side effect without ownership validation"),
                ],
                vuln_type="authz",
                severity="high" if endpoint.method == "DELETE" else "medium",
                confidence="probable",
            )
        )

    logger.info("Built %d attack chain(s) from analysis", len(chains))
    return chains
